server:
  port: 8533
#数据库配置

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/xm1?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2b8&allowPublicKeyRetrieval=true

  main:
    allow-circular-references: true
    
  # 文件上传配置
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 20MB

#配置Mybatis实体和xml映射
mybatis:
#  映射xml
  mapper-locations: classpath:mapper/*.xml
  configuration:
#    配置日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

# 文件上传路径配置
file:
  upload:
    path: ./uploads
    url: http://localhost:8533/uploads
